# Vision models - AutoML CSV file

## Python imports

In [1]:
import pandas as pd
import sklearn.model_selection

## Read vision data sets (train + test)

In [2]:
train_df = pd.read_csv('datasets/vision/train.tsv', sep='\t')
train_df

,label,set,time,source,image,video
0,AT_CH,train,0,Pixel,video_data/AT_CH/train_Pixel_0000_0000.jpeg,../dados_indoor_location/Pixel/Vision/12182683...
1,AT_CH,train,1,Pixel,video_data/AT_CH/train_Pixel_0001_0031.jpeg,../dados_indoor_location/Pixel/Vision/12182683...
2,AT_CH,train,3,Pixel,video_data/AT_CH/train_Pixel_0003_0091.jpeg,../dados_indoor_location/Pixel/Vision/12182683...
3,AT_CH,train,4,Pixel,video_data/AT_CH/train_Pixel_0004_0121.jpeg,../dados_indoor_location/Pixel/Vision/12182683...
4,AT_CH,train,5,Pixel,video_data/AT_CH/train_Pixel_0005_0151.jpeg,../dados_indoor_location/Pixel/Vision/12182683...
...,...,...,...,...,...,...
3738,AT_I2,train,106,Xiaomi,video_data/AT_I2/train_Xiaomi_0106_3181.jpeg,../dados_indoor_location/Xiaomi/Vision/1653920...
3739,AT_I2,train,107,Xiaomi,video_data/AT_I2/train_Xiaomi_0107_3211.jpeg,../dados_indoor_location/Xiaomi/Vision/1653920...
3740,AT_I2,train,108,Xiaomi,video_data/AT_I2/train_Xiaomi_0108_3241.jpeg,../dados_indoor_location/Xiaomi/Vision/1653920...
3741,AT_I2,train,109,Xiaomi,video_data/AT_I2/train_Xiaomi_0109_3271.jpeg,../dados_indoor_location/Xiaomi/Vision/1653920...
3742,AT_I2,train,110,Xiaomi,video_data/AT_I2/train_Xiaomi_0110_3301.jpeg,../dados_indoor_location/Xiaomi/Vision/1653920...

In [5]:
test_df = pd.read_csv('datasets/vision/TS.tsv', sep='\t')
test_df

,label,set,time,source,image,video
0,AT_CH,test,2,Pixel,video_data/AT_CH/test_Pixel_0002_0061.jpeg,../dados_indoor_location/Pixel/Vision/12182683...
1,AT_CH,test,6,Pixel,video_data/AT_CH/test_Pixel_0006_0181.jpeg,../dados_indoor_location/Pixel/Vision/12182683...
2,AT_CH,test,8,Pixel,video_data/AT_CH/test_Pixel_0008_0241.jpeg,../dados_indoor_location/Pixel/Vision/12182683...
3,AT_CH,test,10,Pixel,video_data/AT_CH/test_Pixel_0010_0301.jpeg,../dados_indoor_location/Pixel/Vision/12182683...
4,AT_CH,test,13,Pixel,video_data/AT_CH/test_Pixel_0013_0391.jpeg,../dados_indoor_location/Pixel/Vision/12182683...
...,...,...,...,...,...,...
936,AT_I2,test,85,Xiaomi,video_data/AT_I2/test_Xiaomi_0085_2551.jpeg,../dados_indoor_location/Xiaomi/Vision/1653920...
937,AT_I2,test,90,Xiaomi,video_data/AT_I2/test_Xiaomi_0090_2701.jpeg,../dados_indoor_location/Xiaomi/Vision/1653920...
938,AT_I2,test,98,Xiaomi,video_data/AT_I2/test_Xiaomi_0098_2941.jpeg,../dados_indoor_location/Xiaomi/Vision/1653920...
939,AT_I2,test,102,Xiaomi,video_data/AT_I2/test_Xiaomi_0102_2971.jpeg,../dados_indoor_location/Xiaomi/Vision/1653920...
940,AT_I2,test,111,Xiaomi,video_data/AT_I2/test_Xiaomi_0111_3331.jpeg,../dados_indoor_location/Xiaomi/Vision/1653920...

## Define AutoML sets (train, validation & test)

In [7]:
automl_train_df, automl_valid_df = sklearn.model_selection.train_test_split(train_df, test_size = 0.25, random_state=42)
automl_test_df = test_df

In [13]:
def save_to_csv(df, filename):
    with open(filename, "w") as out:
        df = df.sort_values(['label', 'source', 'time'])
        for item in df.itertuples():
            gcs_path = 'gs://frames_videos/final_dset/' + item.image.replace('video_data/','')
            print('%s,%s' % (gcs_path,item.label), file=out)
            
save_to_csv(automl_train_df, 'datasets/vision/automl/final_dset_train.csv')
save_to_csv(automl_valid_df, 'datasets/vision/automl/final_dset_valid.csv')
save_to_csv(automl_test_df, 'datasets/vision/automl/final_dset_test.csv')

## Save model and convert it to TFLite format

In [7]:
label_map = (train_dataset.class_indices)
label_map

{'AH': 0,
 'AT_CA': 1,
 'AT_CH': 2,
 'AT_I1': 3,
 'AT_I2': 4,
 'AT_M': 5,
 'AT_O1': 6,
 'AT_O2': 7,
 'AT_S': 8,
 'CN': 9,
 'DC': 10,
 'DF': 11,
 'DG': 12,
 'ES': 13,
 'GL': 14,
 'HA': 15,
 'SA': 16,
 'SN': 17,
 'SS': 18,
 'TMA': 19,
 'TS': 20}